# Generated by Django 3.1.3 on 2020-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('des', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
