# Generated by Django 3.1.4 on 2020-12-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='img',
            new_name='img_card',
        ),
        migrations.AddField(
            model_name='service',
            name='img_main',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
