# Generated by Django 3.1.3 on 2020-12-09 16:23

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_is_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.get_image_path),
        ),
    ]
